version: 2
updates:
  # Maintain dependencies for Node.js (Server)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for Flutter (Android)
  - package-ecosystem: "pub"
    directory: "/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
