import os

with open(r"D:\WINDECK\VibeCodeDetector\popup.js", "r", encoding="utf-8") as js_file:
    js = js_file.read()

# We need to store global data for the download
js = js.replace("let currentScore = 0;", "window.lastScanData = data;\n  let currentScore = 0;")

# Add roast logic inside displayResults
roast_logic = """
  // Generate Roast
  const roastBox = document.getElementById('roast-box');
  let roast = "";
  if(data.totalScore <= 15) roast = "Bro actually typed his CSS line-by-line. Respect! 👑";
  else if(data.totalScore <= 35) roast = "Mostly human, but I see you asking ChatGPT for Regex help. 🧐";
  else if(data.totalScore <= 55) roast = "A healthy mix of copy-paste and actual coding. Balanced! ⚖️";
  else if(data.totalScore <= 75) roast = "Vibe coded for sure! I bet v0 built this while you grabbed coffee. ☕";
  else roast = "Did you just tell AI 'make a website' and go to sleep? 💀";
  roastBox.textContent = `"${roast}"`;
"""

js = js.replace("scoreGlow.style.backgroundColor = data.verdictColor;", roast_logic + "\n  scoreGlow.style.backgroundColor = data.verdictColor;")

# Add event listener for download report at the top
download_listener = """
  const downloadReportBtn = document.getElementById('download-report-btn');
  downloadReportBtn.addEventListener('click', () => {
    if(!window.lastScanData) return;
    const d = window.lastScanData;
    
    let reportHTML = `
      <html>
      <head>
        <title>Vibe Code Audit Report</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; }
          h1 { color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
          .score-card { background: #f3f4f6; padding: 20px; border-radius: 8px; margin-bottom: 20px; text-align: center; }
          .score { font-size: 48px; font-weight: bold; color: ${d.verdictColor}; }
          .verdict { font-size: 24px; font-weight: bold; margin-bottom: 10px; }
          .category { margin-bottom: 20px; border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px; }
          .cat-title { font-weight: bold; font-size: 18px; margin-bottom: 10px; display: flex; justify-content: space-between; }
          .critical { color: #dc2626; font-weight: bold; }
          .high { color: #ea580c; }
          .medium { color: #d97706; }
          .low { color: #ca8a04; }
          .clean { color: #16a34a; }
          .prompt { background: #1e293b; color: #38bdf8; padding: 15px; border-radius: 8px; font-family: monospace; white-space: pre-wrap; }
        </style>
      </head>
      <body>
        <h1>🔍 Vibe Code Detector - Audit Report</h1>
        <p><strong>Target URL:</strong> ${d.url}</p>
        <p><strong>Scan Date:</strong> ${new Date(d.timestamp).toLocaleString()}</p>
        
        <div class="score-card">
          <div class="score">${d.totalScore}/100</div>
          <div class="verdict">${d.verdict}</div>
          <p><em>Note: A higher score indicates a higher probability of AI-generated code and potential security shortcuts.</em></p>
        </div>
        
        <h2>Detailed Findings</h2>
    `;
    
    const cats = [
      { key: 'meta', label: 'Meta Fingerprints' },
      { key: 'framework', label: 'Framework & CSS' },
      { key: 'cdn', label: 'CDN & Pipeline' },
      { key: 'quality', label: 'Code Quality' },
      { key: 'security', label: 'Security Flags' }
    ];
    
    cats.forEach(c => {
      const catData = d.categories[c.key];
      reportHTML += `<div class="category">
        <div class="cat-title"><span>${c.label}</span> <span>Score: ${catData.score}/20</span></div>
        <ul>`;
      catData.findings.forEach(f => {
        reportHTML += `<li class="${f.severity}">${f.text}</li>`;
      });
      reportHTML += `</ul></div>`;
    });
    
    reportHTML += `
      <h2>🤖 AI Improvement Prompt</h2>
      <p>Use this prompt in ChatGPT, Cursor, or v0 to fix the detected issues:</p>
      <div class="prompt">${document.getElementById('prompt-text').value}</div>
      
      <p style="text-align: center; margin-top: 40px; color: #6b7280; font-size: 12px;">Generated by Vibe Code Detector Chrome Extension</p>
      
      <script>
        // Auto-trigger print dialog for PDF saving
        window.onload = () => { window.print(); };
      </script>
      </body>
      </html>
    `;
    
    const blob = new Blob([reportHTML], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'VibeCode_Audit_Report.html';
    a.click();
    URL.revokeObjectURL(url);
  });
"""

# Insert the download listener after the copy prompt listener
js = js.replace(
    "copyPromptBtn.textContent = originalText;\n    }, 2000);\n  });",
    "copyPromptBtn.textContent = originalText;\n    }, 2000);\n  });\n" + download_listener
)

with open(r"D:\WINDECK\VibeCodeDetector\popup.js", "w", encoding="utf-8") as js_file:
    js_file.write(js)
