// ============================================================
// VIBE CODE DETECTOR - Content Script
// Scans the current page for AI-generated code signals
// ============================================================

(function () {
  "use strict";

  // ---- 1. META FINGERPRINTS (0-20 pts) ----
  function scanMetaFingerprints() {
    const findings = [];
    let score = 0;
    const html = document.documentElement.outerHTML;
    const headHTML = document.head ? document.head.innerHTML : "";

    // Generator meta tags
    const generatorMeta = document.querySelector('meta[name="generator"]');
    if (generatorMeta) {
      const val = generatorMeta.content.toLowerCase();
      const aiGenerators = ["v0", "bolt", "lovable", "cursor", "windsurf", "replit", "stackblitz", "webcontainer"];
      for (const gen of aiGenerators) {
        if (val.includes(gen)) {
          findings.push({ text: `Generator meta tag detected: "${generatorMeta.content}"`, severity: "high" });
          score += 15;
          break;
        }
      }
    }

    // HTML comments mentioning AI tools
    const commentPattern = /<!--[\s\S]*?-->/g;
    const comments = html.match(commentPattern) || [];
    const aiKeywords = ["generated by", "built with v0", "bolt.new", "lovable", "cursor", "created with ai", "ai-generated", "vibe coded", "windsurf"];
    for (const comment of comments) {
      const lowerComment = comment.toLowerCase();
      for (const kw of aiKeywords) {
        if (lowerComment.includes(kw)) {
          findings.push({ text: `AI-related HTML comment found: "${comment.substring(0, 80)}..."`, severity: "high" });
          score += 10;
          break;
        }
      }
    }

    // Specific data attributes from AI builders
    if (document.querySelector("[data-v0-t]") || html.includes("v0-t=")) {
      findings.push({ text: "Vercel v0 data attribute (data-v0-t) detected", severity: "high" });
      score += 15;
    }

    // Check for lovable meta
    if (html.includes("lovable") || html.includes("gptengineer")) {
      findings.push({ text: "Lovable / GPT Engineer fingerprint detected in source", severity: "high" });
      score += 12;
    }

    // Check for bolt.new patterns
    if (html.includes("bolt.new") || html.includes("stackblitz")) {
      findings.push({ text: "Bolt.new / StackBlitz fingerprint detected", severity: "high" });
      score += 12;
    }

    if (findings.length === 0) {
      findings.push({ text: "No AI tool meta fingerprints found", severity: "clean" });
    }

    return { score: Math.min(score, 20), findings };
  }

  // ---- 2. FRAMEWORK PATTERNS (0-20 pts) ----
  function scanFrameworkPatterns() {
    const findings = [];
    let score = 0;
    const html = document.documentElement.outerHTML;

    // shadcn/ui detection (strong v0 signal)
    const radixAttrs = document.querySelectorAll("[data-radix-collection-item], [data-state], [data-orientation], [data-radix-popper-content-wrapper]");
    if (radixAttrs.length > 0) {
      findings.push({ text: `Radix UI primitives detected (${radixAttrs.length} elements) - Common in v0/shadcn builds`, severity: "medium" });
      score += 8;
    }

    // shadcn class patterns
    const shadcnClasses = ["inline-flex items-center justify-center", "rounded-md text-sm font-medium", "ring-offset-background", "focus-visible:outline-none focus-visible:ring-2", "disabled:pointer-events-none disabled:opacity-50"];
    let shadcnHits = 0;
    for (const cls of shadcnClasses) {
      if (html.includes(cls)) shadcnHits++;
    }
    if (shadcnHits >= 3) {
      findings.push({ text: `shadcn/ui class patterns detected (${shadcnHits}/5 matches) - Strong v0 signal`, severity: "high" });
      score += 10;
    } else if (shadcnHits >= 1) {
      findings.push({ text: `Possible shadcn/ui usage (${shadcnHits}/5 matches)`, severity: "low" });
      score += 3;
    }

    // Next.js detection
    const nextData = document.getElementById("__NEXT_DATA__");
    if (nextData) {
      findings.push({ text: "Next.js framework detected (__NEXT_DATA__)", severity: "info" });
      score += 3;
    }

    // Tailwind detection
    if (html.includes("tailwindcss") || html.match(/class="[^"]*\b(flex|grid|rounded-|bg-|text-|p-|m-|w-|h-)\b[^"]*"/g)) {
      const twElements = document.querySelectorAll('[class*="flex"], [class*="rounded-"], [class*="bg-"]');
      if (twElements.length > 50) {
        findings.push({ text: `Heavy Tailwind CSS usage detected (${twElements.length}+ utility-class elements)`, severity: "medium" });
        score += 5;
      }
    }

    // Lucide icons (common in AI-generated React apps)
    const lucideIcons = document.querySelectorAll('[class*="lucide"], svg[class*="lucide"]');
    if (lucideIcons.length > 0) {
      findings.push({ text: `Lucide icons detected (${lucideIcons.length} instances) - Common in v0/shadcn builds`, severity: "medium" });
      score += 5;
    }

    if (findings.length === 0) {
      findings.push({ text: "No suspicious framework patterns detected", severity: "clean" });
    }

    return { score: Math.min(score, 20), findings };
  }

  // ---- 3. CDN & LAZY LOADING (0-20 pts) ----
  function scanCDNUsage() {
    const findings = [];
    let score = 0;
    const scripts = document.querySelectorAll("script[src]");
    const links = document.querySelectorAll("link[href]");
    const html = document.documentElement.outerHTML;

    // Tailwind CDN (strong vibe-code signal)
    if (html.includes("cdn.tailwindcss.com")) {
      findings.push({ text: "Tailwind loaded via CDN (cdn.tailwindcss.com) - Strong vibe-code signal. Production apps use a build step.", severity: "high" });
      score += 12;
    }

    // Other CDN patterns
    const cdnPatterns = [
      { pattern: "unpkg.com", name: "unpkg CDN" },
      { pattern: "jsdelivr.net", name: "jsDelivr CDN" },
      { pattern: "cdnjs.cloudflare.com", name: "cdnjs CDN" },
      { pattern: "esm.sh", name: "esm.sh CDN" }
    ];
    let cdnCount = 0;
    for (const cdn of cdnPatterns) {
      if (html.includes(cdn.pattern)) {
        cdnCount++;
      }
    }
    if (cdnCount >= 3) {
      findings.push({ text: `Multiple CDN sources detected (${cdnCount}) - Suggests no proper build pipeline`, severity: "high" });
      score += 10;
    } else if (cdnCount >= 1) {
      findings.push({ text: `CDN dependencies found (${cdnCount} source${cdnCount > 1 ? "s" : ""})`, severity: "low" });
      score += 3;
    }

    // Single-file app detection (everything in one HTML)
    const inlineScripts = document.querySelectorAll("script:not([src])");
    let totalInlineJS = 0;
    for (const s of inlineScripts) {
      totalInlineJS += s.textContent.length;
    }
    if (totalInlineJS > 5000 && scripts.length <= 2) {
      findings.push({ text: `Large inline JavaScript detected (${(totalInlineJS / 1024).toFixed(1)}KB) with minimal external scripts - Single-file app pattern`, severity: "medium" });
      score += 8;
    }

    // No bundler/build artifacts
    const hasBundler = html.includes("webpack") || html.includes("vite") || html.includes("_next/static") || html.includes("chunk-") || html.includes(".chunk.");
    if (!hasBundler && scripts.length < 5) {
      findings.push({ text: "No build tool artifacts detected (no webpack/vite chunks)", severity: "low" });
      score += 4;
    }

    if (findings.length === 0) {
      findings.push({ text: "Standard build pipeline detected", severity: "clean" });
    }

    return { score: Math.min(score, 20), findings };
  }

  // ---- 4. CODE QUALITY SIGNALS (0-20 pts) ----
  function scanCodeQuality() {
    const findings = [];
    let score = 0;
    const html = document.documentElement.outerHTML;
    const bodyHTML = document.body ? document.body.innerHTML : "";

    // Repetitive structure detection
    const allDivs = document.querySelectorAll("div");
    const classMap = {};
    for (const div of allDivs) {
      const cls = div.className;
      if (cls && cls.length > 20) {
        classMap[cls] = (classMap[cls] || 0) + 1;
      }
    }
    let repetitiveCount = 0;
    for (const key in classMap) {
      if (classMap[key] >= 5) repetitiveCount++;
    }
    if (repetitiveCount >= 3) {
      findings.push({ text: `Highly repetitive DOM structure detected (${repetitiveCount} duplicated class patterns) - AI tends to copy-paste patterns`, severity: "medium" });
      score += 8;
    }

    // Placeholder / Lorem content
    const placeholderPatterns = ["lorem ipsum", "placeholder", "your text here", "coming soon", "todo:", "fixme:", "example.com", "test@test", "john doe", "jane doe"];
    for (const pattern of placeholderPatterns) {
      if (bodyHTML.toLowerCase().includes(pattern)) {
        findings.push({ text: `Placeholder content found: "${pattern}"`, severity: "medium" });
        score += 4;
        break;
      }
    }

    // Excessive inline styles (AI sometimes mixes approaches)
    const inlineStyleElements = document.querySelectorAll("[style]");
    if (inlineStyleElements.length > 20) {
      findings.push({ text: `Excessive inline styles detected (${inlineStyleElements.length} elements) - Mixed styling approach`, severity: "low" });
      score += 5;
    }

    // Generic IDs
    const genericIdPatterns = ["container", "wrapper", "main-content", "app", "root"];
    let genericIdCount = 0;
    for (const id of genericIdPatterns) {
      if (document.getElementById(id)) genericIdCount++;
    }
    if (genericIdCount >= 3) {
      findings.push({ text: `Generic element IDs detected (${genericIdCount}) - Common in AI scaffolded projects`, severity: "low" });
      score += 4;
    }

    // Accessibility issues (AI often skips a11y)
    const imgsNoAlt = document.querySelectorAll("img:not([alt])");
    const buttonsNoLabel = document.querySelectorAll("button:not([aria-label]):not(:empty)");
    if (imgsNoAlt.length > 3) {
      findings.push({ text: `${imgsNoAlt.length} images missing alt text - AI tools often skip accessibility`, severity: "medium" });
      score += 5;
    }

    if (findings.length === 0) {
      findings.push({ text: "Code quality appears consistent and well-structured", severity: "clean" });
    }

    return { score: Math.min(score, 20), findings };
  }

  // ---- 5. SECURITY RED FLAGS (0-20 pts) ----
  function scanSecurityFlags() {
    const findings = [];
    let score = 0;
    const html = document.documentElement.outerHTML;

    // Exposed API keys patterns
    const keyPatterns = [
      { regex: /sk[-_]live[-_][a-zA-Z0-9]{20,}/g, name: "Stripe Secret Key" },
      { regex: /pk[-_]live[-_][a-zA-Z0-9]{20,}/g, name: "Stripe Publishable Key (Live)" },
      { regex: /AIza[0-9A-Za-z_-]{35}/g, name: "Google API Key" },
      { regex: /sk-[a-zA-Z0-9]{32,}/g, name: "OpenAI API Key" },
      { regex: /ghp_[a-zA-Z0-9]{36}/g, name: "GitHub Personal Access Token" },
      { regex: /xoxb-[0-9]{10,}-[a-zA-Z0-9]{20,}/g, name: "Slack Bot Token" },
      { regex: /eyJhbGciOi[a-zA-Z0-9_-]{50,}\.[a-zA-Z0-9_-]{50,}\.[a-zA-Z0-9_-]{50,}/g, name: "Exposed JWT Token" }
    ];

    for (const kp of keyPatterns) {
      const matches = html.match(kp.regex);
      if (matches) {
        findings.push({ text: `CRITICAL: ${kp.name} possibly exposed in page source!`, severity: "critical" });
        score += 15;
      }
    }

    // .env references in source
    if (html.includes("process.env") || html.includes("import.meta.env")) {
      findings.push({ text: "Environment variable references found in client-side code", severity: "medium" });
      score += 5;
    }

    // Supabase anon key exposed (common in vibe-coded apps)
    if (html.includes("supabase") && html.match(/eyJ[a-zA-Z0-9_-]{100,}/)) {
      findings.push({ text: "Supabase credentials detected in client code - Check RLS policies", severity: "medium" });
      score += 5;
    }

    // Firebase config exposed
    if (html.includes("firebaseConfig") || html.includes("firebase.initializeApp")) {
      findings.push({ text: "Firebase configuration exposed in client code - Ensure security rules are set", severity: "low" });
      score += 3;
    }

    // Console.log left in production
    const inlineScripts = document.querySelectorAll("script:not([src])");
    let consoleLogCount = 0;
    for (const s of inlineScripts) {
      const matches = s.textContent.match(/console\.(log|warn|error|debug)/g);
      if (matches) consoleLogCount += matches.length;
    }
    if (consoleLogCount > 5) {
      findings.push({ text: `${consoleLogCount} console.log statements found in production code - Not cleaned up`, severity: "low" });
      score += 4;
    }

    if (findings.length === 0) {
      findings.push({ text: "No obvious security red flags detected in client code", severity: "clean" });
    }

    return { score: Math.min(score, 20), findings };
  }

  // ---- MAIN SCAN FUNCTION ----
  function runFullScan() {
    const meta = scanMetaFingerprints();
    const framework = scanFrameworkPatterns();
    const cdn = scanCDNUsage();
    const quality = scanCodeQuality();
    const security = scanSecurityFlags();

    const totalScore = meta.score + framework.score + cdn.score + quality.score + security.score;

    let verdict, verdictColor;
    if (totalScore <= 15) {
      verdict = "Hand Coded";
      verdictColor = "#22c55e";
    } else if (totalScore <= 35) {
      verdict = "Mostly Human";
      verdictColor = "#84cc16";
    } else if (totalScore <= 55) {
      verdict = "Partially AI-Assisted";
      verdictColor = "#eab308";
    } else if (totalScore <= 75) {
      verdict = "Likely Vibe Coded";
      verdictColor = "#f97316";
    } else {
      verdict = "Fully Vibe Coded";
      verdictColor = "#ef4444";
    }

    return {
      totalScore,
      verdict,
      verdictColor,
      categories: {
        meta,
        framework,
        cdn,
        quality,
        security
      },
      url: window.location.href,
      title: document.title,
      timestamp: new Date().toISOString()
    };
  }

  // Listen for messages from popup
  chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === "scan") {
      try {
        const results = runFullScan();
        sendResponse(results);
      } catch (err) {
        sendResponse({ error: err.message });
      }
    }
    return true; // Keep message channel open for async response
  });
})();
